/**
 * Database types for TimeFlowPro
 *
 * Note: This file will be auto-generated by Supabase CLI:
 * pnpm supabase:types
 */

// Placeholder - will be generated from Supabase schema
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T];

