/**
 * Database types for TimeFlowPro
 *
 * Re-exports types from auto-generated database.types.ts
 * Generated by: pnpm supabase:types
 */

// Re-export from auto-generated types
export type { Database, Tables, Enums, TablesInsert, TablesUpdate } from '../database.types'
